PACKAGE_NAME="rustinfo_smu"
PACKAGE_VERSION="0.1"
BUILT_MODULE_NAME[0]="rustinfo_smu"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
